-- =============================================================================
-- Daily Workflow Management App — Seed Data
-- =============================================================================
-- This file contains safe, generic sample data for development and testing.
-- It contains NO real company data, real user IDs, real emails, or private info.
--
-- Usage:
--   supabase db seed --file supabase/seed.sql
--
-- Note: Seed data uses a placeholder user_id. Replace this with a real
-- auth.users UUID after creating a test user account, or use the
-- scripts/seed-sample-data.ts script which does this automatically.
-- =============================================================================

-- Replace this with the UUID of a real test user from auth.users.
-- Run: SELECT id FROM auth.users LIMIT 5;
-- to find test user IDs after signing up in the app.
DO $$
DECLARE
  v_user_id uuid;
  v_workflow_id uuid;
  v_summary_id uuid;
BEGIN
  -- Get the first available user (for development only)
  SELECT id INTO v_user_id FROM auth.users LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE NOTICE 'No users found. Sign up in the app first, then run this seed.';
    RETURN;
  END IF;

  RAISE NOTICE 'Seeding sample data for user: %', v_user_id;

  -- -------------------------------------------------------------------------
  -- Workflow: Daily Planning
  -- -------------------------------------------------------------------------
  INSERT INTO public.workflows (id, user_id, name, description, status)
  VALUES (
    gen_random_uuid(),
    v_user_id,
    'Daily Planning',
    'Morning planning workflow for reviewing tasks and setting priorities for the day.',
    'active'
  )
  RETURNING id INTO v_workflow_id;

  -- -------------------------------------------------------------------------
  -- Summary: Example daily summary
  -- -------------------------------------------------------------------------
  INSERT INTO public.summaries (id, user_id, title, content, source, workflow_id)
  VALUES (
    gen_random_uuid(),
    v_user_id,
    'Daily Workflow Summary — Example',
    'This is an example daily summary generated by the agent. In a real workflow, '
    || 'this would contain a concise overview of your day: key highlights, '
    || 'carry-over items, blockers that need attention, and decisions to make. '
    || 'The agent reads context from your work tools and produces this summary '
    || 'each morning before you start working.',
    'agent',
    v_workflow_id
  )
  RETURNING id INTO v_summary_id;

  -- -------------------------------------------------------------------------
  -- Tasks: Sample actionable tasks
  -- -------------------------------------------------------------------------
  INSERT INTO public.tasks (id, user_id, title, description, status, priority, source, workflow_id, summary_id)
  VALUES
    (
      gen_random_uuid(),
      v_user_id,
      'Review open pull request',
      'A pull request is waiting for your review. Check comments and approve or request changes.',
      'open',
      'high',
      'agent',
      v_workflow_id,
      v_summary_id
    ),
    (
      gen_random_uuid(),
      v_user_id,
      'Prepare project update for weekly meeting',
      'Cover what shipped last week, what is in progress, any blockers, and next week''s plan.',
      'open',
      'high',
      'agent',
      v_workflow_id,
      v_summary_id
    ),
    (
      gen_random_uuid(),
      v_user_id,
      'Follow up with vendor on proposal',
      'Initial email was sent. If no response by end of day, follow up by phone.',
      'open',
      'medium',
      'agent',
      v_workflow_id,
      v_summary_id
    ),
    (
      gen_random_uuid(),
      v_user_id,
      'Summarise customer meeting notes',
      'Meeting was this morning. Extract action items and share with the team.',
      'open',
      'medium',
      'user',
      v_workflow_id,
      null
    ),
    (
      gen_random_uuid(),
      v_user_id,
      'Update API documentation',
      'Three new endpoints added last sprint are missing from the public documentation.',
      'open',
      'low',
      'agent',
      v_workflow_id,
      v_summary_id
    ),
    (
      gen_random_uuid(),
      v_user_id,
      'Schedule quarterly planning session',
      'Q1 planning needs to happen next month. Find a time that works for the full team.',
      'open',
      'low',
      'agent',
      null,
      null
    );

  RAISE NOTICE 'Seed complete. Created 1 workflow, 1 summary, and 6 tasks.';
END $$;
